### ISSUE TITLE
Não está funcionando.

### ISSUE THREAD

**Issue by decarvalholucas** [QD-AdminTools-Community/QD-AdminTools-Community.github.io#2]
Boa tarde!

Quando instalei o plugin, simplesmente não acontece nada, precisa ser feito algo complementar pra funcionar?

Fica somente o icone da extensão e quando clico ele aparece um parâmetro de qd-admintools=true mas nada mais do que isso. Se souberem o por que, agradeço!

**Comment by cvscarlos** [comment]
@lcshub após realizar a instalação via https://chrome.google.com/webstore/detail/qd-admin-tools/nhmiadhhhapnkfkmfgagdhoapmenlddc você precisa acessar a loja na URL do VtexCommerceStable.

Então ficaria algo como: https://MINHA_LOJA.vtexcommercestable.com.br/?qd-admintools=true
